[project]
name = 'Quantum-Probability-Manipulation-Market'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.multiverse-branch-speculation]
path = 'contracts/multiverse-branch-speculation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
